### ISSUE TITLE
Game Agent not found despite being installed.

### ISSUE THREAD

**Issue by LexiconCode** [SerpentAI/SerpentAI#102]
* **Operating System:** Linux/**Windows**/macOS
* **Serpent Version: *0.1.10b1* 
* **[Game:](http://agar.io/)** (link to steam page or game)
* **Backend:** **GPU**

### Encountered result
"Exception: Game Agent 'AgarioAgent' wasn't found. Make sure the plugin is installed."
### Steps to reproduce
1.  serpent play AgarioMozillaFirefox AgarioAgent
![image](https://user-images.githubusercontent.com/24551569/31638009-f800e21a-b296-11e7-9386-d6f8ebfd0d7b.png)

I believe the game agent AgarioAgent is installed based on the screenshots.
![image](https://user-images.githubusercontent.com/24551569/31637559-d9ccb5e6-b294-11e7-8287-8aab29d79f0f.png)
![image](https://user-images.githubusercontent.com/24551569/31637594-ffbcff36-b294-11e7-9fbc-a303a9ca31f6.png)

I've tried reinstalling Anaconda and setting up SerpentAI according to the wiki running serpent setup and then run all other commands (i.e. serpent generate game) from within the root directory.

**Comment by nbrochu** [comment]
`serpent play AgarioMozillaFirefox SerpentAgarioAgentGameAgent`

**Comment by LexiconCode** [comment]
Thank you for your reply and it functions as expected.
