### ISSUE TITLE
gvfs-open: steam://run/348840：打开位置出错

### ISSUE THREAD

**Issue by liuhengli** [SerpentAI/SerpentAI#103]
* **Operating System:** Linux
* **Serpent Version:** (e.g. 0.1.6b1)
* **Game:** UFHO2
* **Backend:** GPU

when I launch a game find "gvfs-open: steam://run/348840：打开位置出错：不支持指定位置" and "{'width': 640, 'height': 480, 'x_offset': 79, 'y_offset': 62}".

**Comment by nbrochu** [comment]
I will need more information. On Linux, Serpent.AI tries to use xdg-open, not gvfs-open. Not sure how you ended up with that. What distro and version? What commands did you run? Have the full error?

**Comment by inksong** [comment]
@liuhengli please give more specific informations about the error.
请给出更清晰的问题说明，你遇到什么问题了？
