### ISSUE TITLE
Input Controller Issue with the UP/DOWN/LEFT/RIGHT

### ISSUE THREAD

**Issue by sebastiendecraene** [SerpentAI/SerpentAI#106]
* **Operating System:** Windows
* **Serpent Version:** (e.g. 0.1.6b1)
* **Game:** https://chromedino.com/
* **Backend:** GPU/CPU

### Expected result
To press the selected key

### Encountered result
Nothing happens, every key works except the UP/DOWN/LEFT/RIGHT

### Steps to reproduce

1. 
2. 
3.

**Comment by sebastiendecraene** [comment]
Okay I found the problem: 
It uses the keys on my numpad for some reason when I disable the Num Lock everything works fine.

**Comment by nbrochu** [comment]
This should be fixed in 0.1.12b1. Are you using the latest Serpent.AI? (you can just run `serpent` in the shell to find out)
