### ISSUE TITLE
serpent setup failed

### ISSUE THREAD

**Issue by timothyzhong** [SerpentAI/SerpentAI#109]
* **Operating System:** Linux
* **Serpent Version:**  0.1.12b1

### Expected result
Setup and install dependencies.

### Encountered result
Traceback (most recent call last):
  File "/usr/local/bin/serpent", line 7, in <module>
    from serpent.serpent import execute
  File "/usr/local/lib/python2.7/dist-packages/serpent/serpent.py", line 52
    print(f"\nSerpent.AI v{VERSION}")
                                                     ^
SyntaxError: invalid syntax
### Steps to reproduce

1. Followed install instructions, virtualenv was activated when I enter SerpentAI directory. If I type python3 the version is 3.6.2
2. run "serpent setup" and got the error above.
Seems like it's not running in python 3.6 so the f string caused syntax error.
"pip install SerpentAI" automatically installed it to python2.7. Is this the problem?

**Comment by nbrochu** [comment]
Yes, this error is because it ran using python 2.7.
