### ISSUE TITLE
Need a complete example

### ISSUE THREAD

**Issue by oahzuw** [SerpentAI/SerpentAI#110]
First time I saw this, I was so surprised! I would like to study it in depth and have a more detailed tutorial?
A complete development for a game, video tutorials, can you help me?
 sorry for my bad english!

**Comment by nbrochu** [comment]
There is already a pretty detailed wiki and some full agents coded and available on GitHub. A video series would be great, I agree, but I currently don't have to time to create one. It is on the list.

**Comment by oahzuw** [comment]
@nbrochu   Thanks for the reply,  The environment has been built up by the wiki,  First understand the example on the wiki, Thanks again,
