### ISSUE TITLE
How to debug game agent with pycharm

### ISSUE THREAD

**Issue by wuminorb** [SerpentAI/SerpentAI#112]
Hi:
    Amazing project, and wonderful wiki! But I'm stuck with how to debug game agent with IDE(ie: pycharm).I check the wiki only find the CLI way to start game agent. Is there any python script way to start it? Can anyone help me?

**Comment by nbrochu** [comment]
I am going to resume the weekly development on SerpentAI next weekend. I haven't really needed to use a debugger myself so far in countless experiments. I will try to see what can be done. I know not everyone wants do to so but you can try your luck in #serpent-ai-help on the Discord in the meantime. Plenty of activity there with people with all sorts of setups.

**Comment by dbsxdbsx** [comment]
I have the same question
