### ISSUE TITLE
OSError: [Errno 8] Exec format error: '/home/liugc/project/Xiangqi/run.sh'

### ISSUE THREAD

**Issue by bestlgc** [SerpentAI/SerpentAI#114]
* **Operating System:** Linux
* **Serpent Version:** (e.g. 0.1.6b1)
* **Game:** (python game)
* **Backend:** CPU

### Encountered result
when launching the game it occurs the error:
  _File "/home/liugc/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/liugc/project/Xiangqi/run.sh'_

my config is 
`def __init__(self, **kwargs):
        kwargs["platform"] = "executable"

        kwargs["window_name"] = "Xiangqi"

        
        
        kwargs["executable_path"] = "/home/liugc/project/Xiangqi/run.sh"
        
        

        super().__init__(**kwargs)

        self.api_class = ChineseChessAPI
        self.api_instance = None`

run.sh is : "python example.py"

**Comment by nbrochu** [comment]
Can you try running python directly? Does run.sh have executable permissions?
