### ISSUE TITLE
sdl2 dll load failed

### ISSUE THREAD

**Issue by bestlgc** [SerpentAI/SerpentAI#119]
* **Operating System:** Windows 
`[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ImportError: DLL load failed: 找不到指定的模块。
  File "d:\program\anaconda\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "d:\program\anaconda\lib\site-packages\kivy\core\window\window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[CRITICAL] [App         ] Unable to get a Window, abort.`

**Comment by codetorex** [comment]
Seems sdl2 dependency is missing. Can you try installing kivy with dependencies like this
`pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew kivy` 

[Source](https://kivy.org/docs/installation/installation-windows.html)
