### ISSUE TITLE
Failed building wheel for hiredis

### ISSUE THREAD

**Issue by fengkaijie1995** [SerpentAI/SerpentAI#124]
when execute serpent setup, I met this error 'Failed building wheel for hiredis' and I don't know how to fix it.

**Comment by DavinciDevil** [comment]
I have the same problem,my system was win10

**Comment by netics01** [comment]
Here, too

**Comment by LeonardoDavid** [comment]
@netics01 @DavinciDevil @fengkaijie1995 before running `serpent setup` run this code `conda install -c conda-forge hiredis` to install hirdis it worked for me
