### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'extract_region_from_image'

### ISSUE THREAD

**Issue by cacao1987** [SerpentAI/SerpentAI#126]
* **Operating System:** Windows 10
* **Serpent Version:** lastest
* **Game:** YouMustBuildABoat
* **Backend:** CPU

### Encountered result
In File plugins\SerpentYouMustBuildABoatGamePlugin\files\api\api.py", line 69, in parse_game_board
cell = cv.extract_region_from_image(frame, game.screen_regions.get(screen_region))
AttributeError: module 'cv2.cv2' has no attribute 'extract_region_from_image'

**Comment by sl1msh4dy** [comment]
I found this: 
```
pip install opencv-contrib-python
```
