### ISSUE TITLE
help!why I can't run a executable file in address?

### ISSUE THREAD

**Issue by DavinciDevil** [SerpentAI/SerpentAI#133]
* **Operating System:** Windows10
* **Serpent Version:
* **Game:
* **Backend: GPU

e g :I want run isaac.exe in "G:\Game\afterbirth\isaac-ng.exe",if i double click "isaac-ng.exe" in the path "G:\Game\afterbirth\", it's ok.
but if i run in the SerpentAI,it don't work? appear window of isaac .but it can't work.
somether executable file have not this proble ?such as "G:\Game\Getting Over It\Getting Over It with Bennett Foddy\GettingOverIt.exe" ,i run it in SerpentAI,it's ok! i didn't know why?

ps: forgive my poor english

**Comment by ddugovic** [comment]
Maybe there's a Windows file path issue?  What about:
`"G:/Game/afterbirth/isaac-ng.exe"` or `"G:\\Game\\afterbirth\\isaac-ng.exe"` etc.?

**Comment by DavinciDevil** [comment]
no,path is right.software is opened , but it fail to respond
