### ISSUE TITLE
No matching distribution found for tensorflow-gpu

### ISSUE THREAD

**Issue by coding-boy** [SerpentAI/SerpentAI#136]
* **Operating System:** Windows
* **Serpent Version:0.1.6b1
* **Game:
* **Backend:GPU

### Steps to reproduce

1. "serpent setup" then choose "GPU"
```
Collecting tensorflow-gpu (from -r requirements.txt (line 19))
  Could not find a version that satisfies the requirement tensorflow-gpu (from -r requirements.txt (line 19)) (from versions: )
No matching distribution found for tensorflow-gpu (from -r requirements.txt (line 19))
```

**Comment by nbrochu** [comment]
It seems that Tensorflow that the 1.5.0 RC is out. I'm working on Serpent.AI today so I'll take a look. Thanks for reporting.
