### ISSUE TITLE
[Bug] Occasional error when doing serpent capture

### ISSUE THREAD

**Issue by TeddyHartanto** [SerpentAI/SerpentAI#141]
* **Operating System:** Linux Ubuntu 16.04
* **Serpent.AI Version:** 0.1.12b1
* **Game:** https://tetris.com/play-tetris
* **Backend:** CPU

### Expected result
Serpent should capture frames smoothly

### Encountered result
![image](https://user-images.githubusercontent.com/11240927/35090391-7a93f3ee-fc74-11e7-8f2e-07a8397e8228.png)

### Steps to reproduce
This error happens occasionally only and so far it's at the start of the command. Usually if there's no error and it starts capturing frames, there'll be no error afterwards. As it is an occasional error, I'm still not sure exactly how to reproduce it. I wonder if anybody here have had the same experience?

My current guess is this could be a race condition...? Perhaps before the Game window gets into focus, the Frame Grabber tries to grab the frame. But this is just a guess for now. I'll try to investigate more into it when I have time.

**Comment by nbrochu** [comment]
This will be resolved in the next release. I now wait until the buffer is full before returning frames. 

https://github.com/SerpentAI/SerpentAI/pull/135/files#diff-f69bd2c76ee69cecff9a511607a6a16cR120
