### ISSUE TITLE
Win 10 cannot load intel mkl during plugin install

### ISSUE THREAD

**Issue by peppage** [SerpentAI/SerpentAI#161]
* **Operating System:** Windows 10
* **Serpent.AI Version:** v2018.1.2
* **Game:** All
* **Backend:** GPU/CPU

### Encountered result
OFFSHOOT PLUGIN INSTALL: Installing files...

Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

The procedure entry point mkl_blas_dgem2vu could not be located in the dynamic link library \anaconda\envs\serpent\Library\bin\mkl_intel_thread.dll

### Steps to reproduce

1. serpent generate game
2. enter name and launch location
3. error while installing plugin

The mkl_intel_thread.dll that it's referencing is 2018.0.2.1 from 3/22/2018 so it seems like the latest version. I have several other versions of this file but it seems to be referencing the correct one. Everything seemed fine during the install as well.

**Comment by nbrochu** [comment]
Which Anaconda version are you using? This is a problem involving numpy. It normally works out of the box as Anaconda provides the right files for its supported numpy version. Things can go sideways if you install your own numpy or try to upgrade it.

It's not really a SerpentAI problem, but I'm curious as to how you got there. Last Anaconda I tested the framework with is 5.0 and I see they recently released 5.1.

**Comment by peppage** [comment]
Well interestingly enough it doesn't matter what DLL it specifies in the alert message it was using a different DLL in my windows system32 folder. I took a chance and removed all mkl_ dlls from there and it works.

I had thought since everything was contained in Anaconda it would always look there first for the DLLs.
