### ISSUE TITLE
Incorrect screen region in 4k on launch

### ISSUE THREAD

**Issue by cDurhamMagnet** [SerpentAI/SerpentAI#167]
Please do not post installation issues here. An entire community is available to help over at [http://discuss.serpent.ai](http://discuss.serpent.ai).

* **Operating System:**  Windows 10 x64
* **Serpent.AI Version:** latest at time of posting (ran serpent update, not sure how to get number
* **Game:** diep.io
* **Backend:** CPU

### Expected result
capture full firefox browser window 

### Encountered result
captured incorrect screen region

### Steps to reproduce

1. have a 4k resolution
2. run 'serpent launch DiepIo' (web browser game, running windowed)
3. get wrong parameters for height and width

In addition, I switched resulution to 1920x1080 and the screen regions were correct. Both times I captured frames to verify.

**Comment by nbrochu** [comment]
My guess is you have some form of display scaling going on at 4K on Win 10. This currently causes a mismatch between the display resolution and the capture data. This is an open bug. Give it a try at 100% scaling and see if it's accurate.

#91 Initial bug report

**Comment by cDurhamMagnet** [comment]
Precisely the case! Sorry, I didn't find it when I searched for my issue.

Switched scaling to 100% as suggest and re-logged. Frames now capture as expected. ..and I think I need to move my monitor closer. lol

**Comment by nbrochu** [comment]
I still need to fix this. More and more people are running into it. In a sense, still glad to hear it was that however and not some other issue.
