### ISSUE TITLE
Is this crap abandoned?..

### ISSUE THREAD

**Issue by andrhua** [SerpentAI/SerpentAI#192]
<s>* **Operating System:** Ubuntu 18.04
* **Serpent.AI Version:** The LaTeSt verion POSSIBLE
* **Game:** Cuphead (Licensed Steam version)
* **Backend:** GPU

### Expected result
Be able to launch hello world from guide
### Encountered result
I am not able to do so.
### Steps to reproduce
1. Being alive in October of 2018
2. Find this beautiful (?) framework for completing college project
3. Waste a whole day beating the s... out of the endless stream of dependency errors
4. Install all optional modules with NO errors whatsoever
5. Get stuck at `serpent launch Cuphead`, because I confirmed in THREE ways that window name is really "Cuphead", but serpent still throwing an error 
`Command '['xdotool', 'search', '--onlyvisible', '--name', '^Cuphead$']' returned non-zero exit status 1.`
6. Open Issues tab and realize that dev had stopped answering like 6 months ago
7. Pee your pants after 'The project was born out of admiration for / frustration with OpenAI Universe' that is, for those who don't know, is dead too.
8. Wait for "Viper AI"?...

By the way, Cuphead is running through Steam Play, which uses modified version of Wine, maybe that's the problem, I also tried assign `window_name` to 'Wine', 'Cuphead_steam' but my god I wanna kill myself now. Please send help (do not offer betterhelp)</s>

**Comment by ddugovic** [comment]
I'm unsure if this helps, but if you have one of the games corresponding to the examples (such as Super Hexagon), try that first?
https://github.com/SerpentAI/SerpentAI/wiki/Community-Plugin-Showcase

**Comment by andrhua** [comment]
Even if I miraculously get the plugin working, what's the matter? I want to teach a different game, by various reinforcement learning algorithms

**Comment by andrhua** [comment]
Nevermind. Change the `time.sleep()` in after_launch() for your needs
