### ISSUE TITLE
Some packages failed to install on Windows 10 with serpent setup

### ISSUE THREAD

**Issue by iKlem** [SerpentAI/SerpentAI#25]
__OS__ : Windows 10
__Windows Insider__ : No
__Followed the wiki for the install__ : Yes

---
When launching the `serpent setup` after some times, some package return errors : 
```
Building wheels for collected packages: editdistance, hiredis
  Running setup.py bdist_wheel for editdistance ... error
  Failed building wheel for editdistance
  Running setup.py clean for editdistance
  Running setup.py bdist_wheel for hiredis ... error
  Failed building wheel for hiredis
  Running setup.py clean for hiredis
Failed to build editdistance hiredis
Installing collected packages: hiredis, aioredis, mss, pymsgbox, PyTweening, pyscreeze, PyAutoGUI, pyperclip, win32core, win32gui, markdown, html5lib, protobuf, tensorflow-tensorboard, tensorflow-gpu, Keras, Kivy-Garden, Kivy, pytesseract, txaio, autobahn, editdistance
  Running setup.py install for hiredis ... error
Exception:
Traceback (most recent call last):
  File "C:\HIDDEN\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 59: invalid start byte
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\HIDDEN\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\HIDDEN\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\HIDDEN\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\HIDDEN\Anaconda3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\HIDDEN\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\HIDDEN\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 59: invalid start byte
```

The same errors occurs when installing the packages alone with __pip__.

The solution i've found is to use the command `easy_install PACKAGE_NAME` (for each package with error) and launch again the setup.

Packages i have with these errors : 
- hiredis
- editdistance

**Comment by nbrochu** [comment]
Some packages seem to have linux headers or missing windows headers and depending on what your C++ build setup is on Windows. On Windows 10, and Visual Studio 2017, everything built fine for me but others are seeing issues.

`easy_install PACKAGE_NAME` doesn't fix it for everyone.

I'm looking for a Windows C++ pro that can figure out exactly what determines why it builds or not for people.

**Comment by dbsxdbsx** [comment]
I have the similar issue on win10 like you , but error with other package. And I solved it by using "conda install <package_name>" ,then doing pip install SerpentAI again.

**Comment by JulianNorton** [comment]
**2015** Visual Studio, *not* 2017.
1. http://landinghub.visualstudio.com/visual-cpp-build-tools
2. Anaconda Prompt as ADMIN (right click, run as administrator)
3. `pip install --upgrade SerpentAI`
4. serpent setup

Sometimes it would freeze and I would have to restart.

**Comment by nbrochu** [comment]
Seems like we have a good tips in resolving this issue on Windows. I'll close the issue and link to it in the Windows install wiki page. Thank you all for the solutions.
