### ISSUE TITLE
About the executable files cannot be loaded problem

### ISSUE THREAD

**Issue by GallopingKylin** [SerpentAI/SerpentAI#26]
Hi, i try to use the executable file to run the program, the config file like this:
`
def __init__(self, **kwargs):
        kwargs["platform"] = "executable"
        kwargs["window_name"] = "Adobe Flash Player 25"   
        kwargs["app_args"] = None
        kwargs["executable_path"] = "mygame"
        super().__init__(**kwargs)
        self.api_class = mygameAPI
        self.api_instance = None
`
but when it runs command "serpent launch mygame", the error occured
`Exception: Game 'mygame' wasn't found. Make sure the plugin is installed.`
could you help me?

**Comment by nbrochu** [comment]
`serpent launch` is to be used with the game name you gave to `serpent generate game`.

`kwargs["executable_path"]` needs to be an absolute path to the game's executable or a command in PATH

Can you make a gist with your full game plugin perhaps?

**Comment by GallopingKylin** [comment]
When I use **_serpent generate game_** to start generating again, another error was happended
```
What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame):
MyGame
How is the game launched? (One of: 'steam', 'executable'):
executable
c:\programdata\anaconda3\lib\site-packages\offshoot\base.py:38: UserWarning: 'offshoot.yml' not found! Using default configuration.
  warnings.warn("'offshoot.yml' not found! Using default configuration.")
c:\programdata\anaconda3\lib\site-packages\offshoot\base.py:38: UserWarning: 'offshoot.yml' not found! Using default configuration.
  warnings.warn("'offshoot.yml' not found! Using default configuration.")
OFFSHOOT: Attempting to install SerpentMyGameGamePlugin...
c:\programdata\anaconda3\lib\site-packages\offshoot\base.py:38: UserWarning: 'offshoot.yml' not found! Using default configuration.
  warnings.warn("'offshoot.yml' not found! Using default configuration.")

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...


OFFSHOOT PLUGIN INSTALL: Installing files...


There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kylin\MyGame\plugins\SerpentMyGameGamePlugin\plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentMyGameGamePlugin)
  File "c:\programdata\anaconda3\lib\site-packages\offshoot\base.py", line 178, in executable_hook
    plugin_class.install()
  File "c:\programdata\anaconda3\lib\site-packages\offshoot\plugin.py", line 35, in install
    cls.install_files()
  File "c:\programdata\anaconda3\lib\site-packages\offshoot\plugin.py", line 118, in install_files
    raise e
  File "c:\programdata\anaconda3\lib\site-packages\offshoot\plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "c:\programdata\anaconda3\lib\site-packages\offshoot\plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins\SerpentMyGameGamePlugin\files\serpent_MyGame_game.py => Game
```
So, what should i do next?

**Comment by nbrochu** [comment]
I'll apply a fix to Offshoot tomorrow so we can see what actual exception is happening. Most of the people with issues have the same exception because the plugin engine catches the real one and outputs its own. Luckily I also control the plugin engine so I can fix this.

Thank you for your patience. It's been a busy first day!

**Comment by nbrochu** [comment]
If you encounter *offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable*, something went wrong in your setup. It is unlikely to be an issue with the Serpent.AI codebase itself. Make sure you are in the proper virtualenv. Try going in `ipython` or  `python` and execute the following statements:

`import serpent.game`

`import serpent.game_agent`

You can try getting some help from the community by pasting any error that shows up in *#project-serpent-help* on [Discord](https://discord.gg/9D5SuxH).
