### ISSUE TITLE
reshape size mismatch

### ISSUE THREAD

**Issue by pyloque** [SerpentAI/SerpentAI#31]
(serpent) ➜  SerpentAI serpent launch Doodle
{'width': 683, 'height': 386, 'x_offset': 0, 'y_offset': 43}
(serpent) ➜  SerpentAI serpent play Doodle SerpentDoodleGameAgent
{'width': 683, 'height': 386, 'x_offset': 0, 'y_offset': 43}
Traceback (most recent call last):
  File "/Users/qianwp/Envs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 233, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 157, in play
    game_frame = self.grab_latest_frame()
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 215, in grab_latest_frame
    3
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/frame_grabber.py", line 74, in get_frames
    frame_array = np.fromstring(frame_bytes, dtype="uint8").reshape(frame_shape)
ValueError: cannot reshape array of size 796704 into shape (386,683,3)

**Comment by pyloque** [comment]
same as #30

**Comment by pyloque** [comment]
In [1]: 796704/386/3
Out[1]: 688.0

5 pixels gap

**Comment by pyloque** [comment]
```
        for i in frame_buffer_indices:
            frame_bytes = redis_client.lindex(config["frame_grabber"]["redis_key"], i)
            frame_shape = list(frame_shape)  # monkey
            frame_shape[1] += 5  # monkey
            frame_array = np.fromstring(frame_bytes, dtype="uint8").reshape(frame_shape)

            game_frame = GameFrame(frame_array)

            game_frame_buffer.add_game_frame(game_frame)
```

monkey solved by above code

**Comment by pyloque** [comment]
well, in game of "welcome to heaven", reshape size is ok, while game state always printed as "PAUSED", may because of the screen not allowed resizing

**Comment by nbrochu** [comment]
uh so it's missing 5px wide? I haven't tried it out myself on macOS  yet, but I have a MBP I can set it up on. I'll try to repro with Doodle God.

**Comment by nbrochu** [comment]
The PAUSED issue has a fix coming for it. As for the resize thing in Doodle God, I can't reproduce it as I don't have the game apparently. Are any windows getting resized in game during gameplay?

**Comment by hodgka** [comment]
I  encountered a similar bug with Super Meat Boy, but with 8px instead of 5px. The above fix appears to have solved it though.

**Comment by nbrochu** [comment]
OK I'm trying with Super Meat Boy. I own that one.

**Comment by nbrochu** [comment]
Works for me with SerpentAI 0.1.4b1 and the following Game class:

```python
class SerpentSuperMeatBoyGame(Game, metaclass=Singleton):

    def __init__(self, **kwargs):
        kwargs["platform"] = "steam"

        kwargs["window_name"] = "SuperMeatBoy"

        kwargs["app_id"] = "40800"
        kwargs["app_args"] = None
        

        super().__init__(**kwargs)

        self.api_class = SuperMeatBoyAPI
        self.api_instance = None
```

Reopen if still seeing the issue with a latest SerpentAI.

**Comment by nbrochu** [comment]
#62
