### ISSUE TITLE
Game not receiving pyautogui inputs (win10)

### ISSUE THREAD

**Issue by CmdPuretide** [SerpentAI/SerpentAI#32]
The final code given in the Serpent.AI Hello World wiki page does not (always) work:
serpentYourGame_game_agent.py

```
def handle_play(self, game_frame):
        print("Hello World!")

        for i, game_frame in enumerate(self.game_frame_buffer.frames):
            self.visual_debugger.store_image_data(
                game_frame.frame,
                game_frame.frame.shape,
                str(i)
            )

        self.input_controller.tap_key("right")
```
the frames updating in the visual debugger suggest that it is functioning, and adding a print command will confirm, but the game window does not receive the key input.

Temporary fix is to click on the game window, and pressing the key afterward
```
    def handle_play(self, game_frame):

        for i, game_frame in enumerate(self.game_frame_buffer.frames):
            self.visual_debugger.store_image_data(
                game_frame.frame,
                game_frame.frame.shape,
                str(i)
            )
        pyautogui.click(x=100, y=100); pyautogui.press("right")
```

you need to import pyautogui to the handler file.

The fact that clicking on the window resolves the issue would point to a loss of focus somewhere, though it is unknown whether this is the actual issue.

Again, this fix works but is incredibly annoying since it needs to teleport the mouse back to the point you specified every frame. The roundabout solution might be to save the current mouse position, move to the window, click it, and move back to the previous position

**Comment by nbrochu** [comment]
Will investigate. Thanks for reporting!

**Comment by DmitryGulak** [comment]
This may help https://pythonprogramming.net/direct-input-game-python-plays-gta-v/

**Comment by nbrochu** [comment]
Yes! Perhaps we could specify a backend for the InputController that defaults on PyAutoGUI but can be switched to DirectInput if a game requires it. Seems to be a Windows only issue (DirectX?) as PyAutoGUI works in every game I tested on Linux.

**Comment by nbrochu** [comment]
#65
