### ISSUE TITLE
Windows Modern Apps not compatible

### ISSUE THREAD

**Issue by ferrem** [SerpentAI/SerpentAI#35]
I tried to get SerpentAI running on Asphalt StreetStorm, only available through the Windows Store, and I get `OSError: [WinError 4251] This application can only run in the context of an app container.` I assume the problem is the same with other Modern Apps.

**Comment by nbrochu** [comment]
Seems like it's more a Windows issue than a Serpent.AI issue. Want to try this to launch it? [Launching Modern Apps Natively](https://winaero.com/blog/exclusive-how-to-start-a-modern-app-from-desktop-without-going-to-the-metro-start-screen/)

**Comment by ferrem** [comment]
Tried it, ended up with a new error :
`OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by nbrochu** [comment]
You have a free game that's a Modern App I could try to get it working with?

**Comment by ganyuhuoguang** [comment]
yes

**Comment by ferrem** [comment]
I got this error with Asphalt StreetStorm, which is free

**Comment by nbrochu** [comment]
Alright! I added a planned feature to support them. Thanks for reporting! #36
