### ISSUE TITLE
Cann't resize windows in macos

### ISSUE THREAD

**Issue by larry-fuy** [SerpentAI/SerpentAI#50]
I tried to run SerpentAI to control a free game in Steam, "The Ultimatest Battle" on macOS Sierra. However when I execute "serpent play TheUltimatestBattle SerpentTheUltimatestBattleGameAgent" or "serpent launch TheUltimatestBattle", it always spits out an error "applescript.ScriptError: System Events got an error: Can’t set process "The Ultimatest Battle" to {{0}, {0}}. (-10006) app='System Events' range=118-126".
Any idea?

**Comment by nbrochu** [comment]
I can try it on my MPB. Will let you know!

**Comment by nbrochu** [comment]
For now if you set `kwargs["window_name"] = "UB2_steam"` it should work (just tested it).

This does still require a fix in a sense though because that's the process name and not the window title as per the instructions. macOS is way more convoluted than Windows or Linux for window handling.

**Comment by nbrochu** [comment]
Just bumped SerpentAI to 0.1.4b1. The proper way to have the window management work on macOS is to use the process name (the name you see in the top left when you focus the game) and not the window title. I will indicate the wiki to cover this.

In your case: Update to 0.1.4b1 and switch `kwargs["window_name"] = "UB2_steam"`

Thanks for reporting!
