### ISSUE TITLE
Is this framework only support tensorflow or keras?

### ISSUE THREAD

**Issue by dbsxdbsx** [SerpentAI/SerpentAI#51]
I would like to take some other  deep learning framework like mxnet. I just wonder whether it is supported.

**Comment by nbrochu** [comment]
The framework has some convenience stuff provided that use Keras and Tensorflow. This being said, you can absolutely bring your own libraries.  Just setup mxnet on your machine and `pip install mxnet` in the environment you installed SerpentAI in. 

The Game Agent frame handlers receive GameFrame objects that contain image data as numpy ndarrays. What you do with them machine learning wise is up to you.
