### ISSUE TITLE
every serpent command will print "Using TensorFlow backend"

### ISSUE THREAD

**Issue by mingrui** [SerpentAI/SerpentAI#52]
Ubuntu
GTX1080
serpentAI v0.1.3b1

Hi,

This is a minor issue, but for me every serpent command will print

`Using TensoFlow backend.`

I also check my GPU usage and can confirm it's using about 30%

For example if I just type serpent with no other parameters, it will print using tensorflow, use 30% gpu for a few seconds and then the command will "go through", the serpent help menu will be printed and GPU usage will go back to 0%

Thanks!

**Comment by nbrochu** [comment]
Yes. I'm aware of this one and it's annoying. Barely having a module do `import keras` will initialize CUDA. I'm going to take a shot at fixing this today.

**Comment by nbrochu** [comment]
I added a bit of code to mitigate it. But what is really important is to move the import of *CNNInceptionV3ContextClassifier* to just above `context_classifier=`

```python
from serpent.machine_learning.context_classification.context_classifiers.cnn_inception_v3_context_classifier import CNNInceptionV3ContextClassifier
context_classifier = CNNInceptionV3ContextClassifier(input_shape=(384, 512, 3))  # Replace with the shape (rows, cols, channels) of your captured context frames
```

Here is the updated section of the wiki: [https://github.com/SerpentAI/SerpentAI/wiki/Training-a-Context-Classifier#load-the-context-classifier-in-your-game-agent-code](https://github.com/SerpentAI/SerpentAI/wiki/Training-a-Context-Classifier#load-the-context-classifier-in-your-game-agent-code)
