### ISSUE TITLE
Does it support webpage-based game?

### ISSUE THREAD

**Issue by AlexG31** [SerpentAI/SerpentAI#63]
I want to use this wonderful framework for a webpage-based game in Chrome, for example, this game: http://www.neogeofun.com/game.php?id=440

Since it lives in a tab in Chrome, I suppose the process name of the game is "Chrome", and the window name of the game is "Neo Bomberman | Play Retro SNK Neo Geo games online"? 

I got an error saying "offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins/SerpentChromeGamePlugin/files/serpent_Chrome_game.py => Game"

![2017-09-28 4 20 58](https://user-images.githubusercontent.com/10320903/30956207-179524ba-a469-11e7-9ef9-cb92361fd3a5.png)
![2017-09-28 4 22 04](https://user-images.githubusercontent.com/10320903/30956231-37bad168-a469-11e7-8ae1-838163894096.png)

And it seems that this game does not fit in both of the categories(steam and executable), is it possible to make this work?

**Comment by TVdvd** [comment]
It does work, but it's a bit tricky. You have to use the name of the tab that is currently open in chrome. 
I have used it as a test with a pong game: https://pong-2.com/ .
In this case the name of the window is: "Pong 2 - Online Multiplayer Game with Offline Play - Google Chrome".  This can be seen in Windows task manager if you are using Windows. 
In your case, you forgot the "- Google Chrome" at the end which is invisible in the tab name, but is in the name of the window.

**Comment by nbrochu** [comment]
The error you are seeing is because you are not running your `serpent` commands in the directory where you ran `serpent setup`. Serpent.AI has code/skeleton generators like `rails`, `yeoman`, `create-react-app` etc. 

As for the launching web games, I will make a Web Browser GameLauncher today to officially support that. It will be in 0.1.7b1

**Comment by nbrochu** [comment]
#64

**Comment by nbrochu** [comment]
A WebBrowser Game Launcher is now included in 0.7.1b1
