### ISSUE TITLE
Game window re-movement issue

### ISSUE THREAD

**Issue by Vilsol** [SerpentAI/SerpentAI#67]
I have just encountered an interesting problem. I am currently testing this with [Hero Siege](http://store.steampowered.com/app/269210/Hero_Siege/). It starts properly, detects the window properly, and moves it to the top left corner properly.

But here is the problem. It moves itself on the first drawn frame of the game (or similar) to the center of the display, but because Serpent moves the window as soon as it detects its existence, it results in Serpent moving the window and then the game moving the window instantly after.

I am not sure of any other solution other than waiting for ~10ms (or plugin-configurable amount) and checking if the window is still where you expect it to be.

**Comment by nbrochu** [comment]
As discussed on Discord, this is a game-specific issue and the way to address it is to extend or override the `after_launch` callback in your Game plugin. This callback is provided so you can take control of how Serpent.AI acts after the game is launched.
