### ISSUE TITLE
serpent captures wrong part of display

### ISSUE THREAD

**Issue by Yahatix** [SerpentAI/SerpentAI#68]
I'm on MacOS 10.13 using the newest version of serpent
When i try to capture a context i realized that more often then not serpent captures the wrong part of the screen. See this two pictures taken immediately after each other:
![frame_2f8145a3-03a5-4193-96ee-ee89d24769da](https://user-images.githubusercontent.com/21371842/30977450-d83863b8-a477-11e7-8d51-0a34f8e264de.png)
![frame_2fa27a70-5452-4835-aed6-9d96b420f02b](https://user-images.githubusercontent.com/21371842/30977449-d835ba46-a477-11e7-91bd-f4c2f1bb2db2.png)

**Comment by nbrochu** [comment]
I have never been able to reproduce this and have never seen anyone with a similar issue. I'm going to close it down for now. Feel free to reopen if you have solid repro steps.
