### ISSUE TITLE
[request] add a section on the README / Wiki for community projects

### ISSUE THREAD

**Issue by kjullien** [SerpentAI/SerpentAI#70]
Hey,

I like the fact this project aims for modularity with the plugin based approach, this way anyone can contribute to any part of the project.

In this spirit I would like to propose you add a section to mention noteworthy projects made by fans of your library so people can further dive into the lib.

I would also like to recommend the first addition be my personal repository : [🐍 SerpentAI-SuperHexagon ⬡](https://github.com/kjullien/SerpentAI-SuperHexagon) containing both the game plugin as well as the game agent plugin for the Super Hexagon game used in the tutorial of the wiki. For now as I need to gather data and I cannot train models I will keep everything inside a single repo, when there are enough models to justify a repo for each plugin I will take the necessary steps to make that happen.

I tried to search Github for "serpentai" projects but didn't find any other non-dev-team projects other than mine, so I can't recommend another repository for now but I encourage people to version their current projects on Github to widen the variety of the code people can learn from a bit.

Thanks for the great lib and I hope this idea is liked by the community.

**Comment by Vilsol** [comment]
Not a bad idea, Wiki would probably be the best place for a page like that (as it can be community altered and updated)

**Comment by nbrochu** [comment]
I already have a vision for this in the longer run, but it requires a bit of a development effort: I'd like to create a web application that I will serve from plugins.serpent.ai where you can login through GitHub and register some of your repos as Game and GameAgent plugins. It would be browsable for discovery and you would be able to `serpent install` entries from that website.

In the short term, a wiki page is the way to go though. I'll go ahead and create one and update the README to point to it.

**Comment by nbrochu** [comment]
Created the wiki page! [Community Plugin Showcase](https://github.com/SerpentAI/SerpentAI/wiki/Community-Plugin-Showcase)

Also pointed to it in the README.
