### ISSUE TITLE
input_controller.click() not causing a click.

### ISSUE THREAD

**Issue by SHotch** [SerpentAI/SerpentAI#74]
* **Operating System:** Windows 7
* **Serpent Version:** 0.1.6b1
* **Game:** Nuclear Throne
* **Backend:** GPU

### Expected result
input_controller.click() would... you know.. click.
### Encountered result
Anything that calls click(), and or, does pyautogui.click() doesn't actually cause any input to be registered. Neither left nor right clicks actually work for it. Though it could be the game itself.
### Steps to reproduce

1. Not a clue, I tried doing:
self.input_controller.click_screen_region(button=MouseButton.LEFT, screen_region="PLAY")
with PLAY as a valid screen region in the game plugin.
The mouse moves to the desired location, but there is no actual click.

I tried both left and right clicks to either advance or step back through the menus, and no dice.

**Comment by nbrochu** [comment]
#65
