### ISSUE TITLE
Normalization (range scaling)

### ISSUE THREAD

**Issue by Vilsol** [SerpentAI/SerpentAI#92]
* **Operating System:** Linux/Windows/macOS
* **Serpent Version:** 0.1.10b1
* **Game:** N/A
* **Backend:** GPU/CPU

### Expected result

Using the `serpent.cv.scale_range` function to scale a range between min and max.

### Encountered result

An error:

```
----> 1 serpent.cv.scale_range(numpy.array([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8]), -1, 1)

X:\Anaconda3\lib\site-packages\serpent\cv.py in scale_range(n, minimum, maximum)
     37 def scale_range(n, minimum, maximum):
     38     n += -(np.min(n))
---> 39     n /= np.max(n) / (maximum - minimum)
     40     n += minimum
     41

TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

### Steps to reproduce

1. `import numpy, serpent.cv` 
2. `scale_range(numpy.array([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8]), -1, 1)`

There is also a problem where the `scale_range` function will return unstable results, as it takes source min max from the array itself.

For example, passing an array of [-1, 0, 1] would produce an identical array, however, the numbers can be much higher, but on the same network, it would produce different results.

If the same agent would then call it with an array of [-1, 0, 10], the 0 would drastically shift to negative, which would confuse the NN and therefore produce unpredictable results.

My proposal is to require a specification of the source and target min max values:

```
def normalize(state, source_min, source_max, target_min, target_max):
    return ((state - source_min) * (target_max - target_min) / (source_max - source_min)) + target_min
```

That would make sure that output values stay consistent no matter the input array.

**Comment by nbrochu** [comment]
If you want to PR this, I'll merge it in. Please change _state_ to _n_ (i.e. the usual name for a numpy array arg)
