### ISSUE TITLE
macOS Command Key not included in the enum

### ISSUE THREAD

**Issue by eriktaubeneck** [SerpentAI/SerpentAI#94]
* **Operating System:** Linux/Windows/macOS
* **Serpent Version:** (e.g. 0.1.6b1)
* **Game:** executable (BSNES emulator)
* **Backend:** CPU

Want to be able to hit `⌘R` to restart the emulator on setup, but the key is not included in the Keyboard enum. I'm easily able to drop down to `pyautogui` to make it work, i.e.

```
pyautogui.keyDown("command")
self.input_controller.tap_key(KeyboardKey.KEY_R)
pyautogui.keyUp("command")
```

I'm happy to provide a PR. The simplest solution is simple to add it as a new item in the enum, although you could do something fancier to make things more compatible cross platform (command usually does what ctrl does on a Windows PC). That does seem possible too implicit, though.

**Comment by d0p3t** [comment]
I agree, adding a new item to the enum is probably the easiest solution

**Comment by nbrochu** [comment]
This is a quick one. I'm working on Serpent today so I'll add it in. Thanks for reporting.
