### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xncbf** [SerpentAI/SerpentAI#96]
* **Operating System:** Linux/Windows/macOS
Windows
* **Serpent Version:** (e.g. 0.1.6b1)
lastest
* **Game:** (link to steam page or game)
* **Backend:** GPU/CPU
GPU

### Expected result
install
### Encountered result
error
### Steps to reproduce
When running 'serpent setup'
 The same error occurred.

`TypeError: parse() got an unexpected keyword argument 'transport_encoding'`

What should i do?
The html5lib is installed with a version of 0.999999999

**Comment by xncbf** [comment]
I solved it.

I have reinstalled the html 5 lib as follows.

`conda install -c anaconda html5lib`

**Comment by nbrochu** [comment]
This is apparently becomes an issue with pip after installing tensorflow-gpu. Glad you solved it!
