### ISSUE TITLE
[Error] The Plugin definition specifies an invalid pluggable

### ISSUE THREAD

**Issue by xncbf** [SerpentAI/SerpentAI#97]
![image](https://user-images.githubusercontent.com/9462045/31552033-462ae56c-b071-11e7-8ef9-65a0c231265d.png)

this is the result of type `import serpent.game_agent`.
`import serpent.game` is same.

![image](https://user-images.githubusercontent.com/9462045/31551959-12717038-b071-11e7-84cc-a7b4b410f69c.png)

sorry for my English.

**Comment by d0p3t** [comment]
It looks like you have not run `serpent setup`. Make sure you run `serpent setup` and then run all other commands (i.e. `serpent generate game`) from within the root directory where you ran the setup.

See https://github.com/SerpentAI/SerpentAI/wiki/Windows-Installation-Guide#installing-serpentai

**Comment by xncbf** [comment]
@d0p3t  You're right. Thank you.
