### ISSUE TITLE
ModuleNotFoundError: No module named 'plugins.Serpent-Game-

### ISSUE THREAD

**Issue by LexiconCode** [SerpentAI/SerpentAI#98]
* **Operating System:** Linux/**Windows**/macOS
* **Serpent Version: *0.1.10b1* 
* **[Game:](http://agar.io/)** (link to steam page or game)
* **Backend:** **GPU**

### Expected result
....
### Encountered result
TypeError: activate() takes 1 positional argument but 4 were given`
### Steps to reproduce
1.  serpent generate game
2.  How is the game launched? "Agar.io - Mozilla Firefox"
"Agar.io-MozillaFirefox" 
I have tried "AgarioMozillaFirefox"  
3.  How is the game launched? (One of: 'steam', 'executable', 'web_browser'):
web_browser
### Full Traceback - "Agar.io-MozillaFirefox" 
OFFSHOOT: Attempting to install SerpentAgar.io-MozillaFirefoxGamePlugin...
d:\users\user\anaconda3\envs\serpent\python.exe: Error while finding module specification for 'plugins.SerpentAgar.io-MozillaFirefoxGamePlugin.plugin' (ModuleNotFoundError: No module named 'plugins.SerpentAgar')

### Full Traceback - "AgarIoMozillaFirefox" 

OFFSHOOT: Attempting to install SerpentAgarIoMozillaFirefoxGamePlugin...

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...

OFFSHOOT PLUGIN INSTALL: Installing files...

d:\users\user\anaconda3\envs\serpent\lib\site-packages\offshoot\base.py:63: UserWarning: 'serpent.game' does not appear to be a valid module. Skipping!
  warnings.warn("'%s' does not appear to be a valid module. Skipping!" % m)
d:\users\user\anaconda3\envs\serpent\lib\site-packages\offshoot\base.py:63: UserWarning: 'serpent.game_agent' does not appear to be a valid module. Skipping!
  warnings.warn("'%s' does not appear to be a valid module. Skipping!" % m)

There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "d:\users\user\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\user\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\SerpentAI\plugins\SerpentAgarIoMozillaFirefoxGamePlugin\plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentAgarIoMozillaFirefoxGamePlugin)
  File "d:\users\user\anaconda3\envs\serpent\lib\site-packages\offshoot\base.py", line 178, in executable_hook
    plugin_class.install()
  File "d:\users\user\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 35, in install
    cls.install_files()
  File "d:\users\user\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 118, in install_files
    raise e
  File "d:\users\user\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "d:\users\user\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins\SerpentAgarIoMozillaFirefoxGamePlugin\files\serpent_AgarIoMozillaFirefox_game.py => Game

**Comment by d0p3t** [comment]
1. Your game plugin may not contain any special characters or spaces. `AgarIoMozillaFirefox` should work.
2. Make sure you are scoped correctly into your virtual environment and delete any old/invalid folders inside `plugins`

Example:
```bash
What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame):
AgarIo
How is the game launched? (One of: 'steam', 'executable', 'web_browser'):
web_browser
```

**Comment by LexiconCode** [comment]
Do to "PluginError: The Plugin definition specifies an invalid pluggable:" after following your suggestions I reinstalled Anaconda. After that "AgarIoMozillaFirefox" worked. Thank You!
