### ISSUE TITLE
[need help]  serpent train context 8

### ISSUE THREAD

**Issue by xncbf** [SerpentAI/SerpentAI#99]
This problem occurred while I was practicing.

I typed this.
'serpent train context 8'
How should I fix it?

![image](https://user-images.githubusercontent.com/9462045/31624359-6b5e2a4c-b2dd-11e7-94e7-4a7efb0530ae.png)

**Comment by nbrochu** [comment]
This generally happens when you only have 1 context. This is training a classifier so it needs to differentiate between at least 2 contexts.

**Comment by xncbf** [comment]
@nbrochu Thanks! I will let you know after i try.

**Comment by xncbf** [comment]
@nbrochu Another question, but what does 8 mean?

**Comment by inksong** [comment]
@xncbf that means 8 epochs. Check [this](https://github.com/SerpentAI/SerpentAI/wiki/Training-a-Context-Classifier#train-the-context-classifier) first.

**Comment by xncbf** [comment]
@inksong I read this. But i didn't know what does epochs means.
Now I found out through Google Search. Thanks!
